In [1]:
!pip install cirq numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 24.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 532.7/532.7 kB 31.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.5/60.5 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.3/69.3 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.5/596.5 kB 35.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.9/202.9 kB 15.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 80.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 60.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 71.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 57.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━

In [10]:
import cirq
import numpy as np
from math import gcd
import random


def finding(a, N):

    num_qubits = 2 * int(np.log2(N))
    qu = cirq.LineQubit.range(num_qubits)
    c = cirq.Circuit()


    for q in qu[:num_qubits // 2]:
        c.append(cirq.H(q))

    def expo(a, N, control_qubit, target_qubit):
        exp = a ** 2 % N
        c.append(cirq.ControlledGate(cirq.X**exp).on(control_qubit, target_qubit))

    for i, qubit in enumerate(qu[:num_qubits // 2]):
       expo(a, N, qubit, qu[num_qubits // 2 + i])


    def qft(circuit, qubits):
        for i in range(len(qubits)):
            for j in range(i):
                circuit.append(cirq.CZ(qubits[j], qubits[i]) ** (-1 / (2 ** (i - j))))
            circuit.append(cirq.H(qubits[i]))

    qft(c, qu[:num_qubits // 2])

    c.append(cirq.measure(*qu[:num_qubits // 2], key='measurement'))

    simulator = cirq.Simulator()
    result = simulator.run(c, repetitions=10)
    measurements = result.measurements['measurement']
    return measurements


def shors(N, a=None):

    if N % 2 == 0:
        return 2

    if a is None:
        a = random.randint(2, N - 1)
    while gcd(a, N) != 1:
        a = random.randint(2, N - 1)

    print(f"Randomly chosen a: {a}")

    order_measurements = finding(a, N)
    print(f"Quantum order measurements: {order_measurements}")

    r = measurements(order_measurements, N)
    if r % 2 != 0 or pow(a, r // 2, N) == N - 1:
        return None  #

    factor1 = gcd(pow(a, r // 2) - 1, N)
    factor2 = gcd(pow(a, r // 2) + 1, N)

    return factor1, factor2


def measurements(measurements, N):
    r = 2
    return r



def main():
    try:
        N = int(input("Enter composite number N: "))
        a_input = input("Enter base a (leave blank for random selection): ")
        a = int(a_input) if a_input else None

        factors = shors(N, a)
        if factors:
            print(f"Factors of {N}: {factors}")
        else:
            print("Failed to find factors. Retry.")
    except ValueError:
        print("enter valid integers for N and a.")

if __name__ == "__main__":
    main()


Enter composite number N: 17
Enter base a (leave blank for random selection): 
Randomly chosen a: 13
Quantum order measurements: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Factors of 17: (1, 1)
